version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:8

jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/project
          paths: .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run linting:check
  
  check_formatting:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run formatting:check
  
  unit_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run jest

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run build

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to NPM
          command: "echo 'TO DO: DEPLOY'"

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install_dependencies

      - lint:
          requires:
            - install_dependencies

      - check_formatting:
          requires:
            - install_dependencies

      - unit_tests:
          requires:
            - install_dependencies
      
      - build:
          requires:
            - install_dependencies

      - deploy:
          requires:
            - lint
            - check_formatting
            - unit_tests
            - build
          # filters:
          #   tags:
          #     only: /^v.*/
          #   branches:
          #     ignore: /.*/
