version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:8

jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/project
          paths: .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run linting:check
  
  check_formatting:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run formatting:check
  
  unit_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run jest

  compile_to_js:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn clean
      - run: yarn run babel-compile

  generate_type_definitions:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run tsc
      - run: yarn run flowgen dist/index.d.ts -o dist/index.js.flow

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to NPM
          command: "echo 'TO DO: DEPLOY'"

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install_dependencies

      - lint:
          requires:
            - install_dependencies

      - check_formatting:
          requires:
            - install_dependencies

      - unit_tests:
          requires:
            - install_dependencies
      
      - compile_to_js:
          requires:
            - install_dependencies
      
      - generate_type_definitions:
          requires:
            - compile_to_js

      - deploy:
          requires:
            - lint
            - check_formatting
            - unit_tests
            - compile_to_js
            - generate_type_definitions
          # filters:
          #   tags:
          #     only: /^v.*/
          #   branches:
          #     ignore: /.*/
